#
# LuaDist Travis-CI Hook
#

# We assume C build environments
language: c
os: linux
dist: xenial

# Try using multiple Lua Implementations
env:
  - TOOL="gcc"                  # Use native compiler (GCC usually)
  - TOOL="clang"                # Use clang
  - TOOL="i686-w64-mingw32"     # 32bit MinGW
  - TOOL="x86_64-w64-mingw32"   # 64bit MinGW
  - TOOL="arm-linux-gnueabihf"  # ARM hard-float (hf), linux

# Crosscompile builds may fail
matrix:
  allow_failures:
    - env: TOOL="i686-w64-mingw32"
    - env: TOOL="x86_64-w64-mingw32"
    - env: TOOL="arm-linux-gnueabihf"

# Install dependencies
install:
  - git clone https://github.com/cooljeanius/LuaDistTools.git ~/_tools
  - ~/_tools/travis/travis install
  - "sudo apt-get install lua5.1 lua5.1-doc liblua5.1-0 liblua5.1-0-dbg liblua5.1-0-dev"

# Bootstap
before_script:
  - ~/_tools/travis/travis bootstrap

# Build the module
script:
  - "export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/local/lib/pkgconfig:${PKG_CONFIG_PATH}"
  - ~/_tools/travis/travis build || (pwd && echo "PKG_CONFIG_PATH is ${PKG_CONFIG_PATH}" && ./configure --with-pic && make)

# Execute additional tests or commands:
after_script:
  - ~/_tools/travis/travis test || (test -e Makefile && make check && make distcheck)

after_failure:
  - test -e config.log && cat config.log

after_success:
  - test -e Makefile && make check && make distcheck

# Only watch the master branch
branches:
  only:
    - master

# Notify... someone(?) if needed
notifications:
  email:
    on_success: change
    on_failure: always
